on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip

    - name: setup python env
      run: pip install -r requirements.txt

    - name: generate tex
      run: python generate-tex.py > tex/eclab-beamer.tex

    - name: build pdf
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: tex
        root_file: eclab-beamer.tex
        latexmk_use_xelatex: true

    - name: release assets
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          tex/eclab-beamer.tex
          tex/eclab-beamer.pdf
